# name of pipeline workflow
name: Anant terraform workflow 
# trigger action 
# when there is a push happen in master branch pipeline gonna trigger
on: 
  push:
    branches: [ "main" ]  
    paths-ignore:
      - "README.md"
# jobs what actions we are looking for 
jobs:
  infra-build:
    runs-on: ubuntu-latest 
    steps: # what exactly you want to run in ubuntu machine 
    - name: hello world printing 
      run: echo "Hello world"
    
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: installing terraform 
      uses: hashicorp/setup-terraform@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4.3.1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: us-east-2

    - name: verify terraform installation 
      run: terraform version 
    
    - name: checking data
      run: |
        echo "Hello ${{ secrets.AWS_ACCESS_KEY}}"
        ls -al
    
    - name: terraform init
      run: |
        pwd
        ls -a
        cd ./ec2
        ls -a 
        terraform init

    - name: terraform plan
      run: |
        pwd
        ls -a
        cd ./ec2
        ls -a 
        terraform plan

    - name: terraform apply
      run: |
        pwd
        ls -a
        cd ./ec2
        ls -a
        terraform apply -auto-approve
        cd ../Ansible
        pwd 
        ls -a 
        cat Inventory

    # - name: terraform destroy
    #   run: |
    #     pwd
    #     ls -a
    #     cd ./ec2
    #     ls -a
    #     terraform destroy -auto-approve

    - name: uploading inventory or any other data to github artifact  
      uses: actions/upload-artifact@v4
      with:
        name: ansible-artifact
        path: |
          Ansible/Inventory
          ec2/anant-privateKey.pem
          ansible

  infra-ConfigDeploy:
    runs-on: ubuntu-latest 
    needs: infra-build
    steps: # what exactly you want to run in ubuntu machine 
    - name: installing ansible
      run: |
        sudo apt update
        sudo apt install ansible -y

    - name: verify ansible installation
      run: ansible --version

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: download artifact 
      uses: actions/download-artifact@v5
      with:
        name: ansible-artifact

    - name: verify inventory file
      run: |
        pwd
        cat Inventory

    - name: copy inventory file to Ansible directory
      run: |
        cp Inventory Ansible/

    - name: ansible ping inventory
      run: |
        cd Ansible
        pwd
        ls -a
        cat Inventory
        cat ansible.cfg
        ansible hello -m ping